2016-02-07 18:21:37,321 INFO test3 [main]       Starting test with log4j
   Location where log statement called
           java.lang.Thread.getStackTrace(Thread.java:1552)
           bradleyross.library.helpers.ExceptionHelper.logException(ExceptionHelper.java:410)
           bradleyross.library.helpers.ExceptionHelper.logException(ExceptionHelper.java:463)
           bradleyross.library.helpers.ExceptionHelper.info(ExceptionHelper.java:696)
           bradleyross.library.helpers.ExceptionHelper.main(ExceptionHelper.java:958)
 
2016-02-07 18:21:37,322 INFO test3 [main]       Trap and throw in level 2 - level info
   Location of exception
      java.io.IOException: Triggering IOException
      	at bradleyross.library.helpers.ExceptionHelper$Tester.level3(ExceptionHelper.java:914)
      	at bradleyross.library.helpers.ExceptionHelper$Tester.level2(ExceptionHelper.java:907)
      	at bradleyross.library.helpers.ExceptionHelper$Tester.level1(ExceptionHelper.java:899)
      	at bradleyross.library.helpers.ExceptionHelper$Tester.run(ExceptionHelper.java:892)
      	at bradleyross.library.helpers.ExceptionHelper.main(ExceptionHelper.java:959)
   Location where log statement called
           java.lang.Thread.getStackTrace(Thread.java:1552)
           bradleyross.library.helpers.ExceptionHelper.logException(ExceptionHelper.java:410)
           bradleyross.library.helpers.ExceptionHelper.logException(ExceptionHelper.java:463)
           bradleyross.library.helpers.ExceptionHelper.info(ExceptionHelper.java:689)
           bradleyross.library.helpers.ExceptionHelper$Tester.level2(ExceptionHelper.java:909)
           bradleyross.library.helpers.ExceptionHelper$Tester.level1(ExceptionHelper.java:899)
           bradleyross.library.helpers.ExceptionHelper$Tester.run(ExceptionHelper.java:892)
           bradleyross.library.helpers.ExceptionHelper.main(ExceptionHelper.java:959)
 
2016-02-07 18:21:37,323 WARN test3 [main]       Trap and throw in level 2 - level warn
   Location of exception
      java.io.IOException: Triggering IOException
      	at bradleyross.library.helpers.ExceptionHelper$Tester.level3(ExceptionHelper.java:914)
      	at bradleyross.library.helpers.ExceptionHelper$Tester.level2(ExceptionHelper.java:907)
      	at bradleyross.library.helpers.ExceptionHelper$Tester.level1(ExceptionHelper.java:899)
      	at bradleyross.library.helpers.ExceptionHelper$Tester.run(ExceptionHelper.java:892)
      	at bradleyross.library.helpers.ExceptionHelper.main(ExceptionHelper.java:959)
   Location where log statement called
           java.lang.Thread.getStackTrace(Thread.java:1552)
           bradleyross.library.helpers.ExceptionHelper.logException(ExceptionHelper.java:410)
           bradleyross.library.helpers.ExceptionHelper.logException(ExceptionHelper.java:463)
           bradleyross.library.helpers.ExceptionHelper.warn(ExceptionHelper.java:640)
           bradleyross.library.helpers.ExceptionHelper$Tester.level2(ExceptionHelper.java:910)
           bradleyross.library.helpers.ExceptionHelper$Tester.level1(ExceptionHelper.java:899)
           bradleyross.library.helpers.ExceptionHelper$Tester.run(ExceptionHelper.java:892)
           bradleyross.library.helpers.ExceptionHelper.main(ExceptionHelper.java:959)
 
2016-02-07 18:21:37,323 INFO b.l.h.ExceptionHelper [main]       Starting test with org.slf4j
   Location where log statement called
           java.lang.Thread.getStackTrace(Thread.java:1552)
           bradleyross.library.helpers.ExceptionHelper.logException(ExceptionHelper.java:410)
           bradleyross.library.helpers.ExceptionHelper.logException(ExceptionHelper.java:463)
           bradleyross.library.helpers.ExceptionHelper.info(ExceptionHelper.java:696)
           bradleyross.library.helpers.ExceptionHelper.main(ExceptionHelper.java:964)
 
2016-02-07 18:21:37,324 INFO b.l.h.ExceptionHelper [main]       Trap and throw in level 2 - level info
   Location of exception
      java.io.IOException: Triggering IOException
      	at bradleyross.library.helpers.ExceptionHelper$Tester.level3(ExceptionHelper.java:914)
      	at bradleyross.library.helpers.ExceptionHelper$Tester.level2(ExceptionHelper.java:907)
      	at bradleyross.library.helpers.ExceptionHelper$Tester.level1(ExceptionHelper.java:899)
      	at bradleyross.library.helpers.ExceptionHelper$Tester.run(ExceptionHelper.java:892)
      	at bradleyross.library.helpers.ExceptionHelper.main(ExceptionHelper.java:966)
   Location where log statement called
           java.lang.Thread.getStackTrace(Thread.java:1552)
           bradleyross.library.helpers.ExceptionHelper.logException(ExceptionHelper.java:410)
           bradleyross.library.helpers.ExceptionHelper.logException(ExceptionHelper.java:463)
           bradleyross.library.helpers.ExceptionHelper.info(ExceptionHelper.java:689)
           bradleyross.library.helpers.ExceptionHelper$Tester.level2(ExceptionHelper.java:909)
           bradleyross.library.helpers.ExceptionHelper$Tester.level1(ExceptionHelper.java:899)
           bradleyross.library.helpers.ExceptionHelper$Tester.run(ExceptionHelper.java:892)
           bradleyross.library.helpers.ExceptionHelper.main(ExceptionHelper.java:966)
 
2016-02-07 18:21:37,324 WARN b.l.h.ExceptionHelper [main]       Trap and throw in level 2 - level warn
   Location of exception
      java.io.IOException: Triggering IOException
      	at bradleyross.library.helpers.ExceptionHelper$Tester.level3(ExceptionHelper.java:914)
      	at bradleyross.library.helpers.ExceptionHelper$Tester.level2(ExceptionHelper.java:907)
      	at bradleyross.library.helpers.ExceptionHelper$Tester.level1(ExceptionHelper.java:899)
      	at bradleyross.library.helpers.ExceptionHelper$Tester.run(ExceptionHelper.java:892)
      	at bradleyross.library.helpers.ExceptionHelper.main(ExceptionHelper.java:966)
   Location where log statement called
           java.lang.Thread.getStackTrace(Thread.java:1552)
           bradleyross.library.helpers.ExceptionHelper.logException(ExceptionHelper.java:410)
           bradleyross.library.helpers.ExceptionHelper.logException(ExceptionHelper.java:463)
           bradleyross.library.helpers.ExceptionHelper.warn(ExceptionHelper.java:640)
           bradleyross.library.helpers.ExceptionHelper$Tester.level2(ExceptionHelper.java:910)
           bradleyross.library.helpers.ExceptionHelper$Tester.level1(ExceptionHelper.java:899)
           bradleyross.library.helpers.ExceptionHelper$Tester.run(ExceptionHelper.java:892)
           bradleyross.library.helpers.ExceptionHelper.main(ExceptionHelper.java:966)
 
2016-02-07 18:21:37,324 INFO test3 [main]       Starting test with org.log4j2
   Location where log statement called
           java.lang.Thread.getStackTrace(Thread.java:1552)
           bradleyross.library.helpers.ExceptionHelper.logException(ExceptionHelper.java:410)
           bradleyross.library.helpers.ExceptionHelper.logException(ExceptionHelper.java:463)
           bradleyross.library.helpers.ExceptionHelper.info(ExceptionHelper.java:696)
           bradleyross.library.helpers.ExceptionHelper.main(ExceptionHelper.java:972)
 
2016-02-07 18:21:37,325 INFO b.l.h.ExceptionHelper [main]       Trap and throw in level 2 - level info
   Location of exception
      java.io.IOException: Triggering IOException
      	at bradleyross.library.helpers.ExceptionHelper$Tester.level3(ExceptionHelper.java:914)
      	at bradleyross.library.helpers.ExceptionHelper$Tester.level2(ExceptionHelper.java:907)
      	at bradleyross.library.helpers.ExceptionHelper$Tester.level1(ExceptionHelper.java:899)
      	at bradleyross.library.helpers.ExceptionHelper$Tester.run(ExceptionHelper.java:892)
      	at bradleyross.library.helpers.ExceptionHelper.main(ExceptionHelper.java:974)
   Location where log statement called
           java.lang.Thread.getStackTrace(Thread.java:1552)
           bradleyross.library.helpers.ExceptionHelper.logException(ExceptionHelper.java:410)
           bradleyross.library.helpers.ExceptionHelper.logException(ExceptionHelper.java:463)
           bradleyross.library.helpers.ExceptionHelper.info(ExceptionHelper.java:689)
           bradleyross.library.helpers.ExceptionHelper$Tester.level2(ExceptionHelper.java:909)
           bradleyross.library.helpers.ExceptionHelper$Tester.level1(ExceptionHelper.java:899)
           bradleyross.library.helpers.ExceptionHelper$Tester.run(ExceptionHelper.java:892)
           bradleyross.library.helpers.ExceptionHelper.main(ExceptionHelper.java:974)
 
2016-02-07 18:21:37,325 WARN b.l.h.ExceptionHelper [main]       Trap and throw in level 2 - level warn
   Location of exception
      java.io.IOException: Triggering IOException
      	at bradleyross.library.helpers.ExceptionHelper$Tester.level3(ExceptionHelper.java:914)
      	at bradleyross.library.helpers.ExceptionHelper$Tester.level2(ExceptionHelper.java:907)
      	at bradleyross.library.helpers.ExceptionHelper$Tester.level1(ExceptionHelper.java:899)
      	at bradleyross.library.helpers.ExceptionHelper$Tester.run(ExceptionHelper.java:892)
      	at bradleyross.library.helpers.ExceptionHelper.main(ExceptionHelper.java:974)
   Location where log statement called
           java.lang.Thread.getStackTrace(Thread.java:1552)
           bradleyross.library.helpers.ExceptionHelper.logException(ExceptionHelper.java:410)
           bradleyross.library.helpers.ExceptionHelper.logException(ExceptionHelper.java:463)
           bradleyross.library.helpers.ExceptionHelper.warn(ExceptionHelper.java:640)
           bradleyross.library.helpers.ExceptionHelper$Tester.level2(ExceptionHelper.java:910)
           bradleyross.library.helpers.ExceptionHelper$Tester.level1(ExceptionHelper.java:899)
           bradleyross.library.helpers.ExceptionHelper$Tester.run(ExceptionHelper.java:892)
           bradleyross.library.helpers.ExceptionHelper.main(ExceptionHelper.java:974)
 
